### ISSUE TITLE
Unable to use with auth and without auth

### ISSUE THREAD

**Issue by johntdyer** [BigBoot/AutoKuma#22]
I have tried w/ auth and without auth, with username and with none, ect but I cant get this thing to work.  Whats strange is that the number 1883 keeps showing up in the stack but I have no idea where it is coming from... it does not exist anywhere in my dockerfile

```
  autokuma:
    container_name: autokuma
    image: ghcr.io/bigboot/autokuma:latest
    restart: unless-stopped
    environment:
      AUTOKUMA__KUMA__URL: http://uptime-kuma:3001
      # AUTOKUMA__KUMA__USERNAME: Uptime%20Kuma
      # AUTOKUMA__KUMA__PASSWORD: redacted
      RUST_BACKTRACE: 1
      AUTOKUMA__KUMA__CALL_TIMEOUT: 20
      AUTOKUMA__KUMA__CONNECT_TIMEOUT: 20
      AUTOKUMA__TAG_NAME: AutoKuma
      AUTOKUMA__TAG_COLOR: "#42C0FB"
      # AUTOKUMA__DEFAULT_SETTINGS: |-
      #    docker.docker_container: {{container_name}}
      #    http.max_redirects: 10
      #    *.max_retries: 3
      AUTOKUMA__DOCKER__SOCKET: /var/run/docker.sock
      AUTOKUMA__DOCKER__LABEL_PREFIX: kuma
      AUTOKUMA__LOG_DIR: /var/log/autokuma
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/pve/proxmox_nfs/shared-storage/autokuma:/var/log/autokuma
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
```
```
 2024-04-10T16:36:04.492Z WARN  autokuma::sync      > Encountered error during sync: It looks like the server is expecting a username/password, but none was provided
➜  autokuma docker logs autokuma -f

                .:::.                                      .:::.
              .===-====:                                :-===--==:
             .==.    .:==-.        ..........         :==-.    .==:
             -=-        :===--====================---==:        -==
             -=-          :===-..              ..:===-          :==
             -=-            ::                    .-.           -==
             :==                                                ==-
              ==.                                              .==.
             :==-                                              -==-
            .====.                                             ====-
            ==-                                                  .==:
           :==                                                    ===
           -==                                                    -==
           -==                                                    :==
           -==               ..        ...       ..               -==
           .==.             :===     -=====.    ====              ==-
            ===              .:.   :==-  :==-    ::              :==.
            .==:                  :==:    .==-                  .==:
             .==.                :==:      .==-                .==-
              .==:              .==:        .==:              .==:
               .==-             ==-          :==             :==:
                .-==:          :==            -=-          .-==.
                  .===.        ==.   .::::..   ==.       .-==:
                    :===.     :=-  ==========. :==     .-==:
                      .===:   ==.  -=========  .==.  .-==:
                        .-==-:==    .======:    ==-:===:
                           :-===:      ...     .====:.
                              :==-.          .-==:
                                :====---:--====:
                                   .::----::.
                            _           _  __
              /\           | |         | |/ /
             /  \    _   _ | |_   ___  | ' /  _   _  _ __ ___    __ _
            / /\ \  | | | || __| / _ \ |  <  | | | || '_ ` _ \  / _` |
           / ____ \ | |_| || |_ | (_) || . \ | |_| || | | | | || (_| |
          /_/    \_\ \__,_| \__| \___/ |_|\_\ \__,_||_| |_| |_| \__,_|

 2024-04-10T16:36:07.040Z WARN  kuma_client::util > The server rejected the login: Incorrect username or password.
 2024-04-10T16:36:07.040Z WARN  kuma_client::util > Error while sending event: The server rejected the login: Incorrect username or password.
thread 'tokio-runtime-worker' panicked at /usr/src/autokuma/kuma-client/src/client.rs:166:70:
called `Result::unwrap()` on an `Err` value: Error("invalid type: integer `1883`, expected a string", line: 0, column: 0)
stack backtrace:
   0:     0x56261ec5f45c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x56261ec5f45c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56261ec5f45c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56261ec5f45c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56261ec8a5c0 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x56261ec8a5c0 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x56261ec5c8bf - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x56261ec5f244 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56261ec5f244 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56261ec60847 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x56261ec605af - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x56261ec60cc8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x56261ec60bae - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x56261ec5f926 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x56261ec60912 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x56261e56cef5 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x56261e56d433 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x56261e7845c1 - kuma_client::client::Worker::on_event::{{closure}}::hfddbe6ec5884c57f
  18:     0x56261e77f076 - kuma_client::client::Worker::connect::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h3bf2cc8081b31dce
  19:     0x56261e7a51a5 - tokio::runtime::task::core::Core<T,S>::poll::h21f461232a597765
  20:     0x56261e677d97 - tokio::runtime::task::harness::Harness<T,S>::poll::h1be9b051bf73a22c
  21:     0x56261eb5aceb - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h58e79617ddc5b6cb
  22:     0x56261eb59e90 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h328aa11a8cbd2ff9
  23:     0x56261eb47792 - tokio::runtime::context::set_scheduler::h4b75cd949e356791
  24:     0x56261eb4bfdf - tokio::runtime::context::runtime::enter_runtime::h25179a6048e4c557
  25:     0x56261eb593e8 - tokio::runtime::scheduler::multi_thread::worker::run::h5465053c03b42d72
  26:     0x56261eb3db93 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h7a44ea55d42cd0cc
  27:     0x56261eb5e827 - tokio::runtime::task::core::Core<T,S>::poll::h63944f40587d45e1
  28:     0x56261eb3bd5a - tokio::runtime::task::harness::Harness<T,S>::poll::hbee75dd155d085f2
  29:     0x56261eb526b1 - tokio::runtime::blocking::pool::Inner::run::h12527357f3dc5518
  30:     0x56261eb5c1e7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65d6633220851fd5
  31:     0x56261eb46929 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1389ce9d8cd9649b
  32:     0x56261ec64195 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc7eafaff61e32df9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  33:     0x56261ec64195 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6ba4a5de48dd2304
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  34:     0x56261ec64195 - std::sys::unix::thread::Thread::new::thread_start::he469335aef763e45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
  35:     0x764ae6629134 - <unknown>
  36:     0x764ae66a8a40 - clone
  37:                0x0 - <unknown>
 2024-04-10T16:36:16.000Z WARN  kuma_client::client > Timeout while waiting for Kuma to get ready...
 2024-04-10T16:36:16.000Z WARN  autokuma::sync      > Encountered error during sync: It looks like the server is expecting a username/password, but none was provided
 2024-04-10T16:36:21.057Z WARN  kuma_client::util   > The server rejected the login: Incorrect username or password.
 2024-04-10T16:36:21.057Z WARN  kuma_client::util   > Error while sending event: The server rejected the login: Incorrect username or password.
thread 'tokio-runtime-worker' panicked at /usr/src/autokuma/kuma-client/src/client.rs:166:70:
called `Result::unwrap()` on an `Err` value: Error("invalid type: integer `1883`, expected a string", line: 0, column: 0)
stack backtrace:
   0:     0x56261ec5f45c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x56261ec5f45c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56261ec5f45c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56261ec5f45c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56261ec8a5c0 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x56261ec8a5c0 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x56261ec5c8bf - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x56261ec5f244 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56261ec5f244 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56261ec60847 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x56261ec605af - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x56261ec60cc8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x56261ec60bae - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x56261ec5f926 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x56261ec60912 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x56261e56cef5 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x56261e56d433 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x56261e7845c1 - kuma_client::client::Worker::on_event::{{closure}}::hfddbe6ec5884c57f
  18:     0x56261e77f076 - kuma_client::client::Worker::connect::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h3bf2cc8081b31dce
  19:     0x56261e7a51a5 - tokio::runtime::task::core::Core<T,S>::poll::h21f461232a597765
  20:     0x56261e677d97 - tokio::runtime::task::harness::Harness<T,S>::poll::h1be9b051bf73a22c
  21:     0x56261eb5abbe - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h58e79617ddc5b6cb
  22:     0x56261eb5a0da - tokio::runtime::scheduler::multi_thread::worker::Context::run::h328aa11a8cbd2ff9
  23:     0x56261eb47792 - tokio::runtime::context::set_scheduler::h4b75cd949e356791
  24:     0x56261eb4bfdf - tokio::runtime::context::runtime::enter_runtime::h25179a6048e4c557
  25:     0x56261eb593e8 - tokio::runtime::scheduler::multi_thread::worker::run::h5465053c03b42d72
  26:     0x56261eb3db93 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h7a44ea55d42cd0cc
  27:     0x56261eb5e827 - tokio::runtime::task::core::Core<T,S>::poll::h63944f40587d45e1
  28:     0x56261eb3bd5a - tokio::runtime::task::harness::Harness<T,S>::poll::hbee75dd155d085f2
  29:     0x56261eb526b1 - tokio::runtime::blocking::pool::Inner::run::h12527357f3dc5518
  30:     0x56261eb5c1e7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65d6633220851fd5
  31:     0x56261eb46929 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1389ce9d8cd9649b
  32:     0x56261ec64195 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc7eafaff61e32df9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  33:     0x56261ec64195 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6ba4a5de48dd2304
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  34:     0x56261ec64195 - std::sys::unix::thread::Thread::new::thread_start::he469335aef763e45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
  35:     0x764ae6629134 - <unknown>
  36:     0x764ae66a8a40 - clone
  37:                0x0 - <unknown>
 2024-04-10T16:36:30.016Z WARN  kuma_client::client > Timeout while waiting for Kuma to get ready...
 2024-04-10T16:36:30.016Z WARN  autokuma::sync      > Encountered error during sync: It looks like the server is expecting a username/password, but none was provided
 2024-04-10T16:36:35.072Z WARN  kuma_client::util   > The server rejected the login: Incorrect username or password.
 2024-04-10T16:36:35.072Z WARN  kuma_client::util   > Error while sending event: The server rejected the login: Incorrect username or password.
thread 'tokio-runtime-worker' panicked at /usr/src/autokuma/kuma-client/src/client.rs:166:70:
called `Result::unwrap()` on an `Err` value: Error("invalid type: integer `1883`, expected a string", line: 0, column: 0)
stack backtrace:
   0:     0x56261ec5f45c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x56261ec5f45c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56261ec5f45c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56261ec5f45c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56261ec8a5c0 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x56261ec8a5c0 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x56261ec5c8bf - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x56261ec5f244 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56261ec5f244 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56261ec60847 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x56261ec605af - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x56261ec60cc8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x56261ec60bae - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x56261ec5f926 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x56261ec60912 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x56261e56cef5 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x56261e56d433 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x56261e7845c1 - kuma_client::client::Worker::on_event::{{closure}}::hfddbe6ec5884c57f
  18:     0x56261e77f076 - kuma_client::client::Worker::connect::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h3bf2cc8081b31dce
  19:     0x56261e7a51a5 - tokio::runtime::task::core::Core<T,S>::poll::h21f461232a597765
  20:     0x56261e677d97 - tokio::runtime::task::harness::Harness<T,S>::poll::h1be9b051bf73a22c
  21:     0x56261eb5abbe - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h58e79617ddc5b6cb
  22:     0x56261eb5a0da - tokio::runtime::scheduler::multi_thread::worker::Context::run::h328aa11a8cbd2ff9
  23:     0x56261eb47792 - tokio::runtime::context::set_scheduler::h4b75cd949e356791
  24:     0x56261eb4bfdf - tokio::runtime::context::runtime::enter_runtime::h25179a6048e4c557
  25:     0x56261eb593e8 - tokio::runtime::scheduler::multi_thread::worker::run::h5465053c03b42d72
  26:     0x56261eb3db93 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h7a44ea55d42cd0cc
  27:     0x56261eb5e827 - tokio::runtime::task::core::Core<T,S>::poll::h63944f40587d45e1
  28:     0x56261eb3bd5a - tokio::runtime::task::harness::Harness<T,S>::poll::hbee75dd155d085f2
  29:     0x56261eb526b1 - tokio::runtime::blocking::pool::Inner::run::h12527357f3dc5518
  30:     0x56261eb5c1e7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65d6633220851fd5
  31:     0x56261eb46929 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1389ce9d8cd9649b
  32:     0x56261ec64195 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc7eafaff61e32df9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  33:     0x56261ec64195 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6ba4a5de48dd2304
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
  34:     0x56261ec64195 - std::sys::unix::thread::Thread::new::thread_start::he469335aef763e45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
  35:     0x764ae6629134 - <unknown>
  36:     0x764ae66a8a40 - clone
  37:                0x0 - <unknown>
 2024-04-10T16:36:44.032Z WARN  kuma_client::client > Timeout while waiting for Kuma to get ready...
 2024-04-10T16:36:44.032Z WARN  autokuma::sync      > Encountered error during sync: It looks like the server is expecting a username/password, but none was provided
 2024-04-10T16:36:49.173Z WARN  kuma_client::util   > The server rejected the login: Incorrect username or password.
```

**Comment by johntdyer** [comment]
FWIW I installed kuma-cli on my mac and worked just fine .... I also exec'ed into the container and confirmed connectivity to the URL ...

**Comment by BigBoot** [comment]
Can you please run with `RUST_LOG=kuma_client=trace` set, this should print out every received message from uptime kuma and then look for the number 1883 in the output. Please **DO NOT** attach the output here as it may contain sensitive information.

**Comment by johntdyer** [comment]
have not been able to reproduce, I'll close this for now and reopen if necessary
