### ISSUE TITLE
Kuma-cli: Invalid type: null, expected a string

### ISSUE THREAD

**Issue by PassiHD2004** [BigBoot/AutoKuma#43]
This panic occurs on any option/command and latest git and on release as well

Uptime Kuma version: `1.23.13`
Kuma-Cli Version: `v0.6.0-2bb0efcb`

I have tried setting the url to the proxied url (behind nginx), as well as "http://localhost:3001", same issue

Command: `RUST_BACKTRACE=full cargo run --bin kuma -- --url=redacted --username=redacted --password=redacted monitor list`

Backtrace:
```
thread 'tokio-runtime-worker' panicked at /home/blexyel/testing/AutoKuma/kuma-client/src/client.rs:179:74:
called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a string", line: 0, column: 0)
stack backtrace:
   0:     0x55f8769b2526 - std::backtrace_rs::backtrace::libunwind::trace::h6e4a662bea54ccfc
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55f8769b2526 - std::backtrace_rs::backtrace::trace_unsynchronized::hb42b4eb2797d9c0e
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f8769b2526 - std::sys_common::backtrace::_print_fmt::h2bc261f3223f4e4d
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55f8769b2526 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9cca0343d66d16a8
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55f8769dd780 - core::fmt::rt::Argument::fmt::h8b666c45176be671
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/fmt/rt.rs:142:9
   5:     0x55f8769dd780 - core::fmt::write::h4311bce0ee536615
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/fmt/mod.rs:1120:17
   6:     0x55f8769aefbf - std::io::Write::write_fmt::h0685c51539d0a0cd
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/io/mod.rs:1846:15
   7:     0x55f8769b2304 - std::sys_common::backtrace::_print::h25f19b1d64e81f86
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55f8769b2304 - std::sys_common::backtrace::print::h2fb8f70628a241ed
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55f8769b39d7 - std::panicking::default_hook::{{closure}}::h05093fe2e3ef454d
  10:     0x55f8769b3739 - std::panicking::default_hook::h5ac38aa38e0086d2
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:292:9
  11:     0x55f8769b3e68 - std::panicking::rust_panic_with_hook::hed79743dc8b4b969
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:781:13
  12:     0x55f8769b3d42 - std::panicking::begin_panic_handler::{{closure}}::ha437b5d58f431abf
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:659:13
  13:     0x55f8769b2a26 - std::sys_common::backtrace::__rust_end_short_backtrace::hd98e82d5b39ec859
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55f8769b3a94 - rust_begin_unwind
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
  15:     0x55f8755f9bd5 - core::panicking::panic_fmt::hc69c4d258fe11477
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
  16:     0x55f8755fa213 - core::result::unwrap_failed::hff299ec748d62aab
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1649:5
  17:     0x55f8758727e8 - core::result::Result<T,E>::unwrap::h493f0625f97d6ff3
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1073:23
  18:     0x55f8758727e8 - kuma_client::client::Worker::on_event::{{closure}}::h62e9a0e79be3eb8f
                               at /home/blexyel/testing/AutoKuma/kuma-client/src/client.rs:179:42
  19:     0x55f875870660 - kuma_client::client::Worker::connect::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h4232af960dee1c21
                               at /home/blexyel/testing/AutoKuma/kuma-client/src/client.rs:1052:46
  20:     0x55f875ad7762 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::hc22531b0b04580c5
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:328:17
  21:     0x55f875ad63bb - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h2cf1d21b8a1e2038
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/loom/std/unsafe_cell.rs:16:9
  22:     0x55f875ad63bb - tokio::runtime::task::core::Core<T,S>::poll::hcd690f692e56d194
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:317:13
  23:     0x55f8759188a1 - tokio::runtime::task::harness::poll_future::{{closure}}::hf32c5f61985a4a0f
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:485:19
  24:     0x55f8756583a3 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hcb6fa0e6d925088b
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panic/unwind_safe.rs:272:9
  25:     0x55f875b18a65 - std::panicking::try::do_call::ha9eaf48741062588
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:554:40
  26:     0x55f875b1c55b - __rust_try
  27:     0x55f875b148c8 - std::panicking::try::h44a9458d7a735dd0
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:518:19
  28:     0x55f875b4e6aa - std::panic::catch_unwind::h5b0ec277a4e308d6
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panic.rs:142:14
  29:     0x55f87591713e - tokio::runtime::task::harness::poll_future::hf82e4d4a2f3861d9
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:473:18
  30:     0x55f87591a28c - tokio::runtime::task::harness::Harness<T,S>::poll_inner::he6fb48bf728c1ee7
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:208:27
  31:     0x55f87591d4a3 - tokio::runtime::task::harness::Harness<T,S>::poll::h931e216b36557fbf
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:153:15
  32:     0x55f875b51b8b - tokio::runtime::task::raw::poll::h9dee36c9fdfe8ba7
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:271:5
  33:     0x55f8763a7007 - tokio::runtime::task::raw::RawTask::poll::h7b1f6f9867dc4535
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:201:18
  34:     0x55f876344962 - tokio::runtime::task::LocalNotified<S>::run::h48aa2282e81a94a3
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/mod.rs:416:9
  35:     0x55f87636858d - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h2afa0662a3bfa12e
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:576:13
  36:     0x55f8763683e4 - tokio::runtime::coop::with_budget::h7f6418069017b9d7
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:107:5
  37:     0x55f8763683e4 - tokio::runtime::coop::budget::he5ec71f3dc9f397a
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/coop.rs:73:5
  38:     0x55f8763683e4 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hfe212cf26fb897ac
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  39:     0x55f876367c5d - tokio::runtime::scheduler::multi_thread::worker::Context::run::h2d2a17d5275586d2
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:538:24
  40:     0x55f8763676d9 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}::h647cd05aedf06a91
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  41:     0x55f876363390 - tokio::runtime::context::scoped::Scoped<T>::set::hcb6dbb3e82ce999b
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/scoped.rs:40:9
  42:     0x55f87638d68b - tokio::runtime::context::set_scheduler::{{closure}}::h8f048419715e8157
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context.rs:176:26
  43:     0x55f876357ef0 - std::thread::local::LocalKey<T>::try_with::ha640acc369e73c1e
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/thread/local.rs:286:16
  44:     0x55f876356ebb - std::thread::local::LocalKey<T>::with::h85da35380a2c41f0
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/thread/local.rs:262:9
  45:     0x55f87638d654 - tokio::runtime::context::set_scheduler::hc1774d9e78a58c0c
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context.rs:176:9
  46:     0x55f8763675e1 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::h58643d20ff0da3b1
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  47:     0x55f876398528 - tokio::runtime::context::runtime::enter_runtime::h9df7f7119c4b3b24
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/context/runtime.rs:65:16
  48:     0x55f87636737c - tokio::runtime::scheduler::multi_thread::worker::run::he053484618c93667
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  49:     0x55f8763671eb - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::hd7289620fb0d036f
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  50:     0x55f87635641e - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h0a1efea209befd2c
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/task.rs:42:21
  51:     0x55f87639a66c - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h05fd83c211863f69
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:328:17
  52:     0x55f87639a51f - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::haad04cfa05889e10
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/loom/std/unsafe_cell.rs:16:9
  53:     0x55f87639a51f - tokio::runtime::task::core::Core<T,S>::poll::hed37442aa5c67292
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/core.rs:317:13
  54:     0x55f87634b8b5 - tokio::runtime::task::harness::poll_future::{{closure}}::h7cf3ea9d96f0b096
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:485:19
  55:     0x55f87639efe4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h04f32a514218fe2d
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panic/unwind_safe.rs:272:9
  56:     0x55f876346ff6 - std::panicking::try::do_call::hcfe1a4dfca2cd2b6
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:554:40
  57:     0x55f876347e1b - __rust_try
  58:     0x55f876346008 - std::panicking::try::h64481d4c05593b6b
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:518:19
  59:     0x55f87634cd5b - std::panic::catch_unwind::hed2e86ae2fefe54c
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panic.rs:142:14
  60:     0x55f87634b10f - tokio::runtime::task::harness::poll_future::h2d35608f65512be5
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:473:18
  61:     0x55f876349373 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::heaa0cad4d353dea6
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:208:27
  62:     0x55f876348e57 - tokio::runtime::task::harness::Harness<T,S>::poll::hf734859fbbceb12f
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/harness.rs:153:15
  63:     0x55f8763a727d - tokio::runtime::task::raw::poll::h6d9688e05fbdefb7
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:271:5
  64:     0x55f8763a7007 - tokio::runtime::task::raw::RawTask::poll::h7b1f6f9867dc4535
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/raw.rs:201:18
  65:     0x55f876344a27 - tokio::runtime::task::UnownedTask<S>::run::hbf97b4fbe86b4085
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/task/mod.rs:453:9
  66:     0x55f8763ae127 - tokio::runtime::blocking::pool::Task::run::h0b5686873387e719
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:159:9
  67:     0x55f8763b1229 - tokio::runtime::blocking::pool::Inner::run::h11328980594e826a
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:513:17
  68:     0x55f8763b0f44 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::hb966898fa0b02011
                               at /home/blexyel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:471:13
  69:     0x55f87636c2e6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfc3cf3081b848012
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:155:18
  70:     0x55f876382a82 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h23d09d42069571bb
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/thread/mod.rs:529:17
  71:     0x55f87639f252 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h94d1c00fce918bf5
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panic/unwind_safe.rs:272:9
  72:     0x55f876347063 - std::panicking::try::do_call::he46bf54d1b5a8b5e
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:554:40
  73:     0x55f876347e1b - __rust_try
  74:     0x55f876346911 - std::panicking::try::hf0eaf7cfd735d7d3
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:518:19
  75:     0x55f87638288f - std::panic::catch_unwind::h62eb9546decc4352
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panic.rs:142:14
  76:     0x55f87638288f - std::thread::Builder::spawn_unchecked_::{{closure}}::hd9f7a64b984f2c46
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/thread/mod.rs:528:30
  77:     0x55f87637274f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h41f7f6676d7dbbc4
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
  78:     0x55f8769b6ee5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h32ae492e80523c39
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/alloc/src/boxed.rs:2015:9
  79:     0x55f8769b6ee5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd05b2dc112b7a972
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/alloc/src/boxed.rs:2015:9
  80:     0x55f8769b6ee5 - std::sys::pal::unix::thread::Thread::new::thread_start::h40e6fd3f8ce15a14
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys/pal/unix/thread.rs:108:17
  81:     0x7f689c31e55a - <unknown>
  82:     0x7f689c39ba3c - <unknown>
  83:                0x0 - <unknown>
  ```

**Comment by BigBoot** [comment]
Hi, can you please run with `RUST_LOG="kuma_client=trace"` env variable and look for a log entry starting with `Client::on_any(Custom("maintenanceList")` there seems to be a `null` value somewhere in there where autokuma expects a String...

**Comment by PassiHD2004** [comment]
`{"error":"It looks like the server is expecting a username/password, but none was provided"}`

Username/password is being provided via args tho, which i dont understand

**Comment by PassiHD2004** [comment]
i won't be able to help that much anymore tho, since i switched to a different monitoring solution, but i am still happy to help debugging

**Comment by BigBoot** [comment]
Yes, that error is quite misleading. Due to a limitation in the API it will always fire if an error occurs during the connection process, I've already created an upstream MR to address this which will be included in the uptime kuma 2.0 release. Unfortunately uptime kuma is very `dynamic` with their model handling, i.e. they are just plain objects with attributes being added all over the code so mapping this to a strictly typesafe model like in AutoKuma can get very frustrating...

**Comment by PassiHD2004** [comment]
found this: 
```json
TRACE[kuma_client::client]Client::on_any(Custom("monitorList"), Text([Object {
                "1": Object {
                    "accepted_statuscodes": Array[String("200-299")],
                    "active": Bool(true),
                    "authDomain": Null,
                    "authMethod": Null,
                    "authWorkstation": Null,
                    "basic_auth_pass": Null,
                    "basic_auth_user": Null,
                    "body": Null,
                    "childrenIDs": Array[],
                    "databaseConnectionString": Null,
                    "databaseQuery": Null,
                    "description": Null,
                    "dns_last_result": Null,
                    "dns_resolve_server": String("1.1.1.1"),
                    "dns_resolve_type": String("A"),
                    "docker_container": String(""),
                    "docker_host": Null,
                    "expectedValue": Null,
                    "expiryNotification": Bool(true),
                    "forceInactive": Bool(false),
                    "game": Null,
                    "gamedigGivenPortOnly": Bool(true),
                    "grpcBody": Null,
                    "grpcEnableTls": Bool(false),
                    "grpcMetadata": Null,
                    "grpcMethod": Null,
                    "grpcProtobuf": Null,
                    "grpcServiceName": Null,
                    "grpcUrl": Null,
                    "headers": Null,
                    "hostname": Null,
                    "httpBodyEncoding": String("json"),
                    "id": Number(1),
                    "ignoreTls": Bool(false),
                    "includeSensitiveData": Bool(true),
                    "interval": Number(60),
                    "invertKeyword": Bool(false),
                    "jsonPath": Null,
                    "kafkaProducerAllowAutoTopicCreation": Bool(false),
                    "kafkaProducerBrokers": Null,
                    "kafkaProducerMessage": Null,
                    "kafkaProducerSaslOptions": Null,
                    "kafkaProducerSsl": Bool(false),
                    "kafkaProducerTopic": Null,
                    "keyword": Null,
                    "maintenance": Bool(false),
                    "maxredirects": Number(10),
                    "maxretries": Number(1),
                    "method": String("GET"),
                    "mqttPassword": String(""),
                    "mqttSuccessMessage": String(""),
                    "mqttTopic": String(""),
                    "mqttUsername": String(""),
                    "name": String("passihd personal page"),
                    "notificationIDList": Object {
                        "3": Bool(true)
                    },
                    "oauth_auth_method": Null,
                    "oauth_client_id": Null,
                    "oauth_client_secret": Null,
                    "oauth_scopes": Null,
                    "oauth_token_url": Null,
                    "packetSize": Number(56),
                    "parent": Null,
                    "pathName": String("passihd personal page"),
                    "port": Null,
                    "proxyId": Null,
                    "pushToken": Null,
                    "radiusCalledStationId": Null,
                    "radiusCallingStationId": Null,
                    "radiusPassword": Null,
                    "radiusSecret": Null,
                    "radiusUsername": Null,
                    "resendInterval": Number(0),
                    "retryInterval": Number(60),
                    "screenshot": Null,
                    "tags": Array[],
                    "timeout": Number(48),
                    "tlsCa": Null,
                    "tlsCert": Null,
                    "tlsKey": Null,
                    "type": String("http"),
                    "upsideDown": Bool(false),
                    "url": String("https://www.pingusmc.org"),
                    "weight": Number(2000)
                    }
}
```

I would send the entire output, but its 2000 lines and personal information is in there

**Comment by BigBoot** [comment]
According to the backtrace the problem happens on the `maintenanceList` not the `monitorList` command

**Comment by PassiHD2004** [comment]
idk, i only know that no matter what command i run, it always panics, as soon as it processes received data

**Comment by PassiHD2004** [comment]
i am gonna look through some more logs tho

**Comment by PassiHD2004** [comment]
maybe i can find something

**Comment by PassiHD2004** [comment]
```json
TRACE[kuma_client::client]Client::on_any(Custom("maintenanceList"), Text([Object {
                "2": Object {
                    "active": Bool(true),
                    "cron": String("0 0 1 * *"),
                    "dateRange": Array[Null],
                    "daysOfMonth": Array[Number(1)],
                    "description": String("monthly reboot, idk"),
                    "duration": Number(600),
                    "durationMinutes": Number(10),
                    "id": Number(2),
                    "intervalDay": Number(1),
                    "status": String("scheduled"),
                    "strategy": String("recurring-day-of-month"),
                    "timeRange": Array[Object {
                            "hours": Number(0),
                            "minutes": Number(0),
                            "seconds": Number(0)
                        }, Object {
                            "hours": Number(0),
                            "minutes": Number(10),
                            "seconds": Number(0)
                        }
                    ],
                    "timeslotList": Array[Object {
                            "endDate": String("2024-05-31T22:10:00.000Z"),
                            "startDate": String("2024-05-31T22:00:00.000Z")
                        }
                    ],
                    "timezone": String("Europe/Berlin"),
                    "timezoneOffset": String("+02:00"),
                    "timezoneOption": String("Europe/Berlin"),
                    "title": String("Monthly reboot"),
                    "weekdays": Array[]
                },
                "5": Object {
                    "active": Bool(false),
                    "cron": String(""),
                    "dateRange": Array[Null],
                    "daysOfMonth": Array[],
                    "description": String(""),
                    "duration": Null,
                    "durationMinutes": Number(0),
                    "id": Number(5),
                    "intervalDay": Number(1),
                    "status": String("inactive"),
                    "strategy": String("manual"),
                    "timeRange": Array[Object {
                            "hours": Number(0),
                            "minutes": Number(0)
                        }, Object {
                            "hours": Number(0),
                            "minutes": Number(0)
                        }
                    ],
                    "timeslotList": Array[],
                    "timezone": String("Europe/Berlin"),
                    "timezoneOffset": String("+02:00"),
                    "timezoneOption": String("SAME_AS_SERVER"),
                    "title": String("General Server maintencance"),
                    "weekdays": Array[]
                }
            }
        ]))
```

**Comment by BigBoot** [comment]
`"dateRange": Array[Null],` yeah that's the problem...

**Comment by PassiHD2004** [comment]
why would that happen tho? is that like an upstream bug?

**Comment by PassiHD2004** [comment]
![image](https://github.com/BigBoot/AutoKuma/assets/59457929/c65b1c8b-725e-402e-a9f7-b885c7a0880f)
this is what one of the maintenances looks like.

The date range is an optional field and i assume that isn't accounted for in Autokuma

**Comment by BigBoot** [comment]
But since we found the culprit I can modify the model accordingly, thanks for your help :+1:

**Comment by PassiHD2004** [comment]
no problem
